"""OutrosAtributosDoUsuario

Revision ID: 05c37e10e58c
Revises: 525a36ef8c85
Create Date: 2021-10-13 17:05:00.287999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05c37e10e58c'
down_revision = '525a36ef8c85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('telefone', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('telefone')
        batch_op.drop_column('nome')

    # ### end Alembic commands ###
