"""Coloquei os atributos de rede sociais dentro da entidade usuario

Revision ID: 1ba3670560f3
Revises: 98b003c052a9
Create Date: 2021-10-15 18:27:12.467609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ba3670560f3'
down_revision = '98b003c052a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facebook', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('instagram', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('whatsapp', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('telegram', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('telegram')
        batch_op.drop_column('whatsapp')
        batch_op.drop_column('instagram')
        batch_op.drop_column('facebook')

    # ### end Alembic commands ###
