"""Adicionei a tabela endereço

Revision ID: 245321980dd8
Revises: 05c37e10e58c
Create Date: 2021-10-15 17:09:21.695632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245321980dd8'
down_revision = '05c37e10e58c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endereco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('cidade', sa.String(length=30), nullable=False),
    sa.Column('bairro', sa.String(length=30), nullable=False),
    sa.Column('rua', sa.String(length=30), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario'], ['usuario.id'], name=op.f('fk_endereco_usuario_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_endereco'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('endereco')
    # ### end Alembic commands ###
