"""USUARIO

Revision ID: 525a36ef8c85
Revises: 54e227839b96
Create Date: 2021-10-11 23:10:34.198274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '525a36ef8c85'
down_revision = '54e227839b96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario')),
    sa.UniqueConstraint('username', name=op.f('uq_usuario_username'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    # ### end Alembic commands ###
