"""Coloquei os atributos da entidade endereço dentro da entidade usuario

Revision ID: 98b003c052a9
Revises: 245321980dd8
Create Date: 2021-10-15 17:55:17.718767

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '98b003c052a9'
down_revision = '245321980dd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('endereco')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('cidade', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('bairro', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('rua', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('numero', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('numero')
        batch_op.drop_column('rua')
        batch_op.drop_column('bairro')
        batch_op.drop_column('cidade')
        batch_op.drop_column('estado')

    op.create_table('endereco',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('estado', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('cidade', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('bairro', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('rua', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('numero', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('usuario', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['usuario'], ['usuario.id'], name='fk_endereco_usuario_usuario'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
