"""Tirei a tabela exemplo

Revision ID: f9430128145f
Revises: 1ba3670560f3
Create Date: 2021-10-19 17:07:12.230700

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f9430128145f'
down_revision = '1ba3670560f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('example', schema=None) as batch_op:
        batch_op.drop_index('uq_example_field1')

    op.drop_table('example')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('example',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('field1', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('field2', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('example', schema=None) as batch_op:
        batch_op.create_index('uq_example_field1', ['field1'], unique=False)

    # ### end Alembic commands ###
